version: 2.0.0
name: "dbt_first_project"
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
models:
  staging_layer:
    +materialized: tables
  intermediate_layer:
    +materialized: tables

seeds:
  +schema: seed_schema

